### ISSUE TITLE
Columns don't always have correct order

### ISSUE THREAD

**Issue by poofcakes** [UMCUGenetics/VUSualizer#4]
Local: 
![image](https://user-images.githubusercontent.com/8579642/88654984-63893c00-d0ce-11ea-874f-3be17d6e522d.png)

Test server:
![image](https://user-images.githubusercontent.com/8579642/88655019-713ec180-d0ce-11ea-88e7-b03a0bdf3c29.png)

Might be an issue with the test server, but either way should be looked into.

**Comment by poofcakes** [comment]
Seems it has resolved itself on this specific page /patients for now. It might only occur randomly. It is happening now on /variants page.

The problem already occurs when acquiring the data through datatable.py, so it is likely not a datatables.js problem.
[Local (click)](http://localhost:5000/_get_variant_data?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=desc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1597239219848)
![image](https://user-images.githubusercontent.com/8579642/90021216-3d0ff700-dcb1-11ea-9bbd-92b760e43aa4.png)

Test server:
![image](https://user-images.githubusercontent.com/8579642/90021448-924c0880-dcb1-11ea-9c2e-95214646fc49.png)


Might be due to difference in python version (Python 3.5 is used on test server), or some lower Python package versions. When directly querying mongo at both locations, the results are the same:
![image](https://user-images.githubusercontent.com/8579642/90021391-79435780-dcb1-11ea-8a76-0a9856ff7792.png)

**Comment by FiniDG** [comment]
fixed
